<?php
// $Id$
function fuzzysearch_install() {
  switch ($GLOBALS['db_type']) {
    case 'mysql':
    case 'mysqli':  
      db_query("CREATE TABLE search_index_queue (
        nid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        module VARCHAR( 60 ) NOT NULL,
        timestamp INT( 11 ) NOT NULL
      )");
      
      db_query("CREATE TABLE search_fuzzy_index (
        id int(11) NOT NULL auto_increment,
        sid int(11) NOT NULL,
        trigram varchar(6) character set utf8 NOT NULL,
        completeness double NOT NULL,
        score decimal(8,2) NOT NULL,
        total decimal(8,2) NOT NULL,
        PRIMARY KEY  (`id`)
      )");
      
      break;
    case 'pgsql':
    
      break;
  }
  
  // Queue all content for indexing
  $query = db_query("SELECT nid FROM {node}");
  while ($row = db_fetch_object($query)) {
    fuzzysearch_reindex($row->nid, 'fuzzysearch');
  }
  drupal_set_message('Fuzzysearch Module Installed Successfully.');
  drupal_set_message('Content queued for indexing, please run cron to begin indexing.');
}